artifacts_root: artifacts

data_validation:
  root_dir: artifacts\validation
  data_dir: artifacts\raw_data\customer_churn_removed_col.csv
  status_file: artifacts\validation\status.txt
  make_data:
    train_data: artifacts\validation\train.csv
    test_data: artifacts\validation\test.csv
